In [8]:
import tensorcircuit as tc

tc.set_dtype("complex128")
K = tc.set_backend("tensorflow")

n = 1


def loss(params, n):
    c = tc.Circuit(n)
    for i in range(n):
        c.rx(i, theta=params[0, i])
    for i in range(n):
        c.rz(i, theta=params[1, i])
    loss = 0.0
    for i in range(n):
        loss += c.expectation([tc.gates.z(), [i]])
    return K.real(loss)


vgf = K.jit(K.value_and_grad(loss), static_argnums=1)
params = K.implicit_randn([2, n])
print(vgf(params, n))  # get the quantum loss and the gradient

(<tf.Tensor: shape=(), dtype=float64, numpy=0.7605744130365597>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.64925075],
       [0.        ]], dtype=float32)>)


In [12]:
help(tc.set_backend)

Help on function set_tensornetwork_backend in module tensorcircuit.cons:

set_tensornetwork_backend(backend: Union[str, NoneType] = None, set_global: bool = True) -> Any
    To set the runtime backend of tensorcircuit.
    
    Note: ``tc.set_backend`` and ``tc.cons.set_tensornetwork_backend`` are the same.
    
    :Example:
    
    >>> tc.set_backend("numpy")
    numpy_backend
    >>> tc.gates.num_to_tensor(0.1)
    array(0.1+0.j, dtype=complex64)
    >>>
    >>> tc.set_backend("tensorflow")
    tensorflow_backend
    >>> tc.gates.num_to_tensor(0.1)
    <tf.Tensor: shape=(), dtype=complex64, numpy=(0.1+0j)>
    >>>
    >>> tc.set_backend("pytorch")
    pytorch_backend
    >>> tc.gates.num_to_tensor(0.1)
    tensor(0.1000+0.j)
    >>>
    >>> tc.set_backend("jax")
    jax_backend
    >>> tc.gates.num_to_tensor(0.1)
    DeviceArray(0.1+0.j, dtype=complex64)
    
    :param backend: "numpy", "tensorflow", "jax", "pytorch". defaults to None,
        which gives the same behavior as ``te