In [11]:
import numpy as np # 导入numpy库，并给定别名


In [ ]:
# 数组对象 np.array()

# 初始化

# 直接初始化
# 每个维度对应一层中括号
a = np.array([1, 2, 3])
b = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("直接初始化")
print(a)
print(b)

# 特殊初始化
# 数据默认为64位float
a = np.zeros((3, 2)) # 参数为尺寸，(行, 列)
b = np.ones((2, 3))
print("\n 特殊初始化")
print(a)
print(a.shape) # 给出数组尺寸
# len() 给出数组第一层的大小，如[[...], [...]]会输出2，对于矩阵这就是行数
print(b)

# 序列
a = np.arange(1, 9, 2) # 类似range，参数为开始、结尾和步长（不写默认1，可以为负数），也是包前不包后，参数必须为整数
b = np.linspace(0, 10, 6) # 类似MATLAB的同名函数，在开始和结尾之间等距取值
print("\n 序列")
print(a)
print(b)


直接初始化
[1 2 3]
[[1 0 0]
 [0 1 0]
 [0 0 1]]

 特殊初始化
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
[[1. 1. 1.]
 [1. 1. 1.]]

 序列
[1 3 5 7]
[ 0.  2.  4.  6.  8. 10.]


In [13]:
# 运算

# 同尺寸数组可以按元素进行四则运算 + - * /
# 可以同一个数进行四则运算，相当于把每个元素都与这个数做运算
# np.sqrt(), np.sin(), np.cos(), np.log(), np.power(数组, 幂次) 等函数也是按元素的

# 向量标量积 np.dot(a, b) # 不会自动取复共轭
a = np.array([1j, 2j])
b = np.array([1, 2])
print(np.dot(a, b))

# 矩阵乘法 a @ b
a = np.random.rand(2, 3)
b = np.random.rand(3, 2)
print(a @ b)


5j
[[0.21153592 0.60020963]
 [0.62851233 1.08370194]]


In [14]:
# 索引

# 直接索引
# 下标从0开始
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a[1, 0])
print(a[0:2, 2]) # 注意切片也是包前不包后，而且切片给出一维数组时不区分行列
print(a[:, 0]) # 类似MATLAB的冒号
# 冒号后还可以加一个冒号，给出跨度
print(a[0, ::-1]) # 这相当于给出第一行的降序排列

# 条件索引
print(a[a >= 3])
# 多个条件用 & 和 | 表示与和或，而不是python的and和or
print(a[(a >= 3) & (a % 2 == 0)])

# 注意：列表的切片是新的数据，但是数组的切片仍然是这一部分的内存地址
x0 = np.array([1, 2, 3, 4, 5, 6])
x1 = x0[3:6]
x1[0] = 90
print(x0)

y0 = [1, 2, 3, 4, 5, 6]
y1 = y0[3:6]
y1[0] = 90
print(y0)

6
[3 8]
[1 6]
[5 4 3 2 1]
[ 3  4  5  6  7  8  9 10]
[ 4  6  8 10]
[ 1  2  3 90  5  6]
[1, 2, 3, 4, 5, 6]


In [15]:
# 操作
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax()) # 返回最大（最小）值的索引，从0开始
print(a.mean())
print(a.std()) # 标准差
print(a.sum()) # 全部求和
print(a.sum(axis = 0)) # 在对应维度的方向求和，0对应行，1对应列

1
10
0
9
5.5
2.8722813232690143
55
[ 7  9 11 13 15]
